//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QDSearch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=server.solvex.local;Initial Catalog=avalon;User ID=qdsearch;MultipleA" +
            "ctiveResultSets=True;Connect Timeout=60;Application Name=qdsearch2;Password=!123" +
            "!")]
        public string avalonConnectionString {
            get {
                return ((string)(this["avalonConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=server2.solvex.local;Initial Catalog=avalonWeb;User ID=qdsearch;Multi" +
            "pleActiveResultSets=True;Connect Timeout=60;Application Name=qdsearch2;Password=" +
            "!123!")]
        public string avalonWebConnectionString {
            get {
                return ((string)(this["avalonWebConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=server2.solvex.local;Initial Catalog=SftWebPsDB;User ID=qdsearch;Mult" +
            "ipleActiveResultSets=True;Connect Timeout=60;Application Name=qdsearch2;Password" +
            "=!123!")]
        public string SftWebPsDbConnectionString {
            get {
                return ((string)(this["SftWebPsDbConnectionString"]));
            }
        }
    }
}
