declare @tableName varchar(100), @sql varchar(max)

declare tableCursor cursor local fast_forward for
select name
from sys.tables
where name like 'mwPriceDataTable_%'
order by name 

truncate table mwPriceDataTable

open tableCursor
fetch tableCursor into @tableName
while (@@FETCH_STATUS = 0)
begin

	set @sql = 'insert into mwPriceDataTable (
			[pt_mainplaces]
           ,[pt_addplaces]
           ,[pt_main]
           ,[pt_tourvalid]
           ,[pt_tourcreated]
           ,[pt_tourdate]
           ,[pt_days]
           ,[pt_nights]
           ,[pt_cnkey]
           ,[pt_ctkeyfrom]
           ,[pt_apkeyfrom]
           ,[pt_ctkeyto]
           ,[pt_apkeyto]
           ,[pt_ctkeybackfrom]
           ,[pt_ctkeybackto]
           ,[pt_tourkey]
           ,[pt_tourtype]
           ,[pt_tlkey]
           ,[pt_pricelistkey]
           ,[pt_pricekey]
           ,[pt_price]
           ,[pt_hdkey]
           ,[pt_hdpartnerkey]
           ,[pt_rskey]
           ,[pt_ctkey]
           ,[pt_hdstars]
           ,[pt_pnkey]
           ,[pt_hrkey]
           ,[pt_rmkey]
           ,[pt_rckey]
           ,[pt_ackey]
           ,[pt_childagefrom]
           ,[pt_childageto]
           ,[pt_childagefrom2]
           ,[pt_childageto2]
           ,[pt_hdname]
           ,[pt_tourname]
           ,[pt_pnname]
           ,[pt_pncode]
           ,[pt_rmname]
           ,[pt_rmcode]
           ,[pt_rcname]
           ,[pt_rccode]
           ,[pt_acname]
           ,[pt_accode]
           ,[pt_rsname]
           ,[pt_ctname]
           ,[pt_rmorder]
           ,[pt_rcorder]
           ,[pt_acorder]
           ,[pt_rate]
           ,[pt_toururl]
           ,[pt_hotelurl]
           ,[pt_isenabled]
           ,[pt_chkey]
           ,[pt_chbackkey]
           ,[pt_hdday]
           ,[pt_hdnights]
           ,[pt_chday]
           ,[pt_chpkkey]
           ,[pt_chprkey]
           ,[pt_chbackday]
           ,[pt_chbackpkkey]
           ,[pt_chbackprkey]
           ,[pt_hotelkeys]
           ,[pt_hotelroomkeys]
           ,[pt_hotelstars]
           ,[pt_pansionkeys]
           ,[pt_hotelnights]
           ,[pt_chdirectkeys]
           ,[pt_chbackkeys]
           ,[pt_topricefor]
           ,[pt_hash]
           ,[pt_tlattribute]
           ,[pt_spo]
           ,[pt_hddetails]
           ,[pt_AccmdType]
           ,[pt_autodisabled]
           ,[pt_directFlightAttribute]
           ,[pt_backFlightAttribute])
	select x.[pt_mainplaces]
           ,x.[pt_addplaces]
           ,x.[pt_main]
           ,x.[pt_tourvalid]
           ,x.[pt_tourcreated]
           ,x.[pt_tourdate]
           ,x.[pt_days]
           ,x.[pt_nights]
           ,x.[pt_cnkey]
           ,x.[pt_ctkeyfrom]
           ,x.[pt_apkeyfrom]
           ,x.[pt_ctkeyto]
           ,x.[pt_apkeyto]
           ,x.[pt_ctkeybackfrom]
           ,x.[pt_ctkeybackto]
           ,x.[pt_tourkey]
           ,x.[pt_tourtype]
           ,x.[pt_tlkey]
           ,x.[pt_pricelistkey]
           ,x.[pt_pricekey]
           ,x.[pt_price]
           ,x.[pt_hdkey]
           ,x.[pt_hdpartnerkey]
           ,x.[pt_rskey]
           ,x.[pt_ctkey]
           ,x.[pt_hdstars]
           ,x.[pt_pnkey]
           ,x.[pt_hrkey]
           ,x.[pt_rmkey]
           ,x.[pt_rckey]
           ,x.[pt_ackey]
           ,x.[pt_childagefrom]
           ,x.[pt_childageto]
           ,x.[pt_childagefrom2]
           ,x.[pt_childageto2]
           ,x.[pt_hdname]
           ,x.[pt_tourname]
           ,x.[pt_pnname]
           ,x.[pt_pncode]
           ,x.[pt_rmname]
           ,x.[pt_rmcode]
           ,x.[pt_rcname]
           ,x.[pt_rccode]
           ,x.[pt_acname]
           ,x.[pt_accode]
           ,x.[pt_rsname]
           ,x.[pt_ctname]
           ,x.[pt_rmorder]
           ,x.[pt_rcorder]
           ,x.[pt_acorder]
           ,x.[pt_rate]
           ,x.[pt_toururl]
           ,x.[pt_hotelurl]
           ,x.[pt_isenabled]
           ,x.[pt_chkey]
           ,x.[pt_chbackkey]
           ,x.[pt_hdday]
           ,x.[pt_hdnights]
           ,x.[pt_chday]
           ,x.[pt_chpkkey]
           ,x.[pt_chprkey]
           ,x.[pt_chbackday]
           ,x.[pt_chbackpkkey]
           ,x.[pt_chbackprkey]
           ,x.[pt_hotelkeys]
           ,x.[pt_hotelroomkeys]
           ,x.[pt_hotelstars]
           ,x.[pt_pansionkeys]
           ,x.[pt_hotelnights]
           ,x.[pt_chdirectkeys]
           ,x.[pt_chbackkeys]
           ,x.[pt_topricefor]
           ,x.[pt_hash]
           ,x.[pt_tlattribute]
           ,x.[pt_spo]
           ,x.[pt_hddetails]
           ,x.[pt_AccmdType]
           ,x.[pt_autodisabled]
           ,x.[pt_directFlightAttribute]
           ,x.[pt_backFlightAttribute]
	from ' + @tableName + ' as x with(nolock)
	where charindex('','', pt_hddetails) > 0'

	print @sql
	exec (@sql)

	fetch tableCursor into @tableName
end
close tableCursor
deallocate tableCursor